<?php
				$LOGO = 'LOGO_1248442912.GIF' ;
				$COMPANY_NAME = 'HABC' ;
				$SUPPORT_LOGO_ONLINE = 'SUPPORT_LOGO_ONLINE_1298568684.GIF' ;
				$SUPPORT_LOGO_OFFLINE = 'SUPPORT_LOGO_OFFLINE_1298568696.GIF' ;
				$SUPPORT_LOGO_AWAY = '' ;
				$VISITOR_FOOTPRINT = '1' ;
				$THEME = 'default' ;
				$POLL_TIME = '45' ;
				$INITIATE = '1' ;
				$INITIATE_IMAGE = 'INITIATE_IMAGE_1298568615.JPEG' ;
				$IPNOTRACK = '' ;
				$LANG_PACK = 'brasil' ;?>